export const INFLATION = .04
export const PHASE_ONE_YEARS = 5
export type GoldenNumberV2Input = Record<string, string | number | boolean>
export type GoldenNumberV2Settings = { monthlySpend:number; years:number; capital:number; targetReturn:number; phase1Contribution:number; phase1Return:number; phase2Contribution:number; phase2Return:number; indexPhase1:boolean; indexPhase2:boolean; age:number }
const realRate=(gross:number)=>Math.max(0,gross-INFLATION)
export function goldenNumber(monthlySpend:number, years:number, grossReturn:number) { const r=grossReturn-INFLATION; return r > .0001 ? monthlySpend * 12 * Math.pow(1+INFLATION, years) / r : Infinity }
export function futureValueYears(initial:number, monthly:number, grossReturn:number, years:number, indexed:boolean) { const m=Math.pow(1+realRate(grossReturn),1/12)-1; const annual=Math.pow(1+m,12); let balance=initial; for(let y=0;y<Math.round(years);y++){ const contribution=indexed ? monthly*Math.pow(1+INFLATION,y) : monthly; const annuity=m>0 ? contribution*((annual-1)/m)*(1+m) : contribution*12; balance=balance*annual+annuity } return balance }
export function futureValue(s:GoldenNumberV2Settings, years=s.years) { const y1=Math.min(years,PHASE_ONE_YEARS); return futureValueYears(futureValueYears(s.capital,s.phase1Contribution,s.phase1Return,y1,s.indexPhase1),s.phase2Contribution,s.phase2Return,Math.max(0,years-PHASE_ONE_YEARS),s.indexPhase2) }
export function invested(s:GoldenNumberV2Settings, years=s.years) { let total=s.capital; for(let y=0;y<Math.min(years,PHASE_ONE_YEARS);y++) total += s.phase1Contribution*12*(s.indexPhase1?Math.pow(1+INFLATION,y):1); for(let y=0;y<Math.max(0,years-PHASE_ONE_YEARS);y++) total += s.phase2Contribution*12*(s.indexPhase2?Math.pow(1+INFLATION,y):1); return total }
export function reachedYear(s:GoldenNumberV2Settings) { for(let y=1;y<=s.years+45;y++) if(futureValue(s,y)>=goldenNumber(s.monthlySpend,y,s.targetReturn)) return y; return null }
export function calculateGoldenNumberV2(s:GoldenNumberV2Settings) { const today=goldenNumber(s.monthlySpend,0,s.targetReturn), target=goldenNumber(s.monthlySpend,s.years,s.targetReturn), projected=futureValue(s), totalInvested=invested(s), year=reachedYear(s); return { today,target,projected,totalInvested,returns:Math.max(0,projected-totalInvested),year,series:Array.from({length:Math.max(s.years,year ? Math.min(year+1,s.years+45):s.years)+1},(_,y)=>({year:y,capital:futureValue(s,y),target:goldenNumber(s.monthlySpend,y,s.targetReturn)})) } }
export function countryFromPhone(phone?:string) { const normalized=(phone||'').replace(/[^\d+]/g,''); return normalized.startsWith('+57')||normalized.startsWith('57') ? 'CO' : undefined }
export function currencyForCountry(country?:string) { return country === 'CO' ? 'COP' : 'USD' }
export function incomeRanges(currency:string) { return currency==='COP' ? ['Menos de $2 millones','Entre $2 y $4 millones','Entre $4 y $8 millones','Entre $8 y $15 millones','Más de $15 millones'] : ['Menos de USD 500','Entre USD 500 y 1.000','Entre USD 1.000 y 2.000','Entre USD 2.000 y 4.000','Más de USD 4.000'] }
export function suggestedContribution(income:string,destination:string,currency:string) { const cop:{[key:string]:number}={'Menos de $2 millones':1500000,'Entre $2 y $4 millones':3000000,'Entre $4 y $8 millones':6000000,'Entre $8 y $15 millones':11500000,'Más de $15 millones':20000000}; const usd:{[key:string]:number}={'Menos de USD 500':375,'Entre USD 500 y 1.000':750,'Entre USD 1.000 y 2.000':1500,'Entre USD 2.000 y 4.000':3000,'Más de USD 4.000':5000}; const pct=destination.includes('nada')?.03:destination.includes('yéndose')?.08:destination.includes('banco')?.15:destination.includes('CDT')?.18:.22; const base=(currency==='COP'?cop:usd)[income] || (currency==='COP'?3000000:750); const round=currency==='COP'?50000:25; return Math.max(round,Math.round(base*pct/round)*round) }
